/**
 * The 16-step local demo from the spec, executed against the real contracts on a local Anvil.
 * Steps 1-6 (Anvil + deployments) are done by scripts/demo.sh; this script runs steps 7-16 and prints
 * every number from chain state. It also writes docs/demo-output.md (the README walkthrough).
 *
 *   ./scripts/demo.sh            (starts an isolated Anvil on :8565, deploys, runs this, stops Anvil)
 *
 * No real money anywhere: mock tokens, mock markets, Anvil's published dev keys.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { ANVIL_ACCOUNTS, toFixed, usd, withGasHeadroom } from "@dnv/shared";
import { type Hex, maxUint256 } from "viem";

import { anvilIncreaseTime, createChain } from "./chain/clients";
import { readRawState } from "./chain/reader";
import { loadConfig } from "./config";
import { Keeper } from "./keeper";
import { deltaView, pnlView, positionsView, riskView, strategyView, vaultView } from "./views";

const cfg = loadConfig();
const chain = createChain(cfg);
const c = chain.contracts;
const d = chain.deployment;
const pc = chain.publicClient;
const SIM = ANVIL_ACCOUNTS[0].key;
const GUARDIAN = ANVIL_ACCOUNTS[2].key;
const ALICE = ANVIL_ACCOUNTS[4];
const keeper = new Keeper(chain, null, ANVIL_ACCOUNTS[1].key);

const md: string[] = [];
const out = (s = "") => {
  console.log(s);
  md.push(s);
};
const $ = (x: number, dp = 2) => `${x < 0 ? "-" : ""}$${Math.abs(x).toLocaleString("en-US", { minimumFractionDigits: dp, maximumFractionDigits: dp })}`;
const pct = (bps: number | null) => (bps === null ? "n/a" : `${(bps / 100).toFixed(2)}%`);

async function send(key: string, address: Hex, abi: readonly unknown[], functionName: string, args: readonly unknown[] = []) {
  const w = chain.wallet(key);
  const call = { address, abi: abi as never, functionName: functionName as never, args: args as never, account: w.account };
  const gas = withGasHeadroom(await pc.estimateContractGas(call as never));
  const hash = await w.writeContract({ ...call, gas, chain: w.chain } as never);
  const r = await pc.waitForTransactionReceipt({ hash });
  if (r.status !== "success") throw new Error(`${functionName} reverted`);
  return r;
}

async function setPrice(p: number) {
  const a = toFixed(p, 8);
  await send(SIM, d.ethUsdFeed, c.feed.abi, "setAnswer", [a]);
  await send(SIM, d.ethUsdFallbackFeed, c.fallbackFeed.abi, "setAnswer", [a]);
}

async function currentPrice(): Promise<number> {
  const [, a] = await c.feed.read.latestRoundData();
  return Number(a) / 1e8;
}

/** Advance chain time, republish the price (oracle heartbeat is 1h), run a keeper tick. */
async function day(price?: number) {
  await anvilIncreaseTime(pc, 24 * 3600);
  await setPrice(price ?? (await currentPrice()));
  return keeper.tick();
}

async function state() {
  const s = await readRawState(chain);
  return {
    s,
    vault: vaultView(s, cfg.CHAIN_ID, d.vault, d.usdc),
    pos: positionsView(s, cfg.CHAIN_ID),
    delta: deltaView(s, cfg.CHAIN_ID),
    risk: riskView(s, cfg.CHAIN_ID),
    pnl: pnlView(s, cfg.CHAIN_ID),
    strat: strategyView(s, cfg.CHAIN_ID),
  };
}

function table(rows: Record<string, string | number>) {
  console.table(rows);
  md.push("", "| | |", "|---|---|", ...Object.entries(rows).map(([k, v]) => `| ${k} | ${v} |`), "");
}

async function book(title: string) {
  const { vault, pos, delta, risk } = await state();
  out(`\n**${title}**`);
  table({
    "ETH price": $(pos.ethPrice),
    "vault TVL": $(vault.tvlUsd),
    "share price": vault.sharePrice.toFixed(6),
    "USDC reserve (lending)": $(pos.reserve.suppliedUsd),
    "long leg (WETH lending)": `${pos.long.wethQty.toFixed(4)} ETH = ${$(pos.long.valueUsd)}`,
    "perp short": `${pos.perp.size.toFixed(4)} ETH, equity ${$(pos.perp.equityUsd)}`,
    "net delta": `${delta.deltaBps} bps (${$(delta.netDeltaUsd)})`,
    "hedge ratio": `${(delta.hedgeRatioBps / 100).toFixed(2)}%`,
    leverage: `${pos.perp.leverage.toFixed(2)}x`,
    "liquidation price": pos.perp.liquidationPrice === null ? "n/a" : $(pos.perp.liquidationPrice),
    "distance to liquidation": pct(pos.perp.liquidationDistanceBps),
    "risk state": risk.state,
  });
}

async function main() {
  out("# Delta-Neutral Vault - local demo transcript");
  out("");
  out("Generated by `./scripts/demo.sh` against the real contracts on a local Anvil. Mock markets, no real funds.");

  // ---- steps 1-6 -------------------------------------------------------
  out("\n## Steps 1-6 - chain + deployments");
  out("Anvil started and the full stack deployed by `script/Deploy.s.sol`:");
  table({
    "1. Anvil": cfg.RPC_URL,
    "2. mock USDC": d.usdc,
    "3. ETH/USD oracle (primary / fallback)": `${d.ethUsdFeed} / ${d.ethUsdFallbackFeed}`,
    "4. lending market": d.lendingPool,
    "5. perpetual market": d.perpMarket,
    "6. ERC-4626 vault": d.vault,
    "strategy / rebalancer / risk": `${d.strategyManager} / ${d.rebalanceManager} / ${d.riskManager}`,
  });

  // ---- 7. deposit ----------------------------------------------------------
  out("\n## Step 7 - Alice deposits $100,000");
  await send(ALICE.key, d.usdc, c.usdc.abi, "faucet", [toFixed(100_000, 6)]);
  await send(ALICE.key, d.usdc, c.usdc.abi, "approve", [d.vault, maxUint256]);
  const preview = await c.vault.read.previewDeposit([toFixed(100_000, 6)]);
  await send(ALICE.key, d.vault, c.vault.abi, "deposit", [toFixed(100_000, 6), ALICE.address]);
  const depositTs = Number((await pc.getBlock()).timestamp);
  const shares = await c.vault.read.balanceOf([ALICE.address]);
  out(`previewDeposit said ${(Number(preview) / 1e12).toFixed(6)} shares; minted ${(Number(shares) / 1e12).toFixed(6)} shares (1 share = 1 USDC at inception).`);

  // ---- 8 + 9. allocate + hedge ------------------------------------------------
  out("\n## Steps 8-9 - keeper allocates capital and opens the hedge");
  const [plan] = await c.rebalanceManager.read.previewRebalance();
  out(`On-chain plan: sweep ${$(usd(plan.sweepIdle))} idle, buy ${$(usd(plan.longUsdDelta))} of WETH, post ${$(usd(plan.marginDelta))} margin, short to 100% hedge. Estimated cost ${$(usd(plan.estimatedCost))}.`);
  await keeper.tick();
  await book("Book after deployment");

  // ---- 10. ETH +20% ----------------------------------------------------------
  out("\n## Step 10 - ETH +20% over four days (keeper runs daily)");
  const p0 = await currentPrice();
  let rebalances = 0;
  for (let i = 1; i <= 4; i++) if ((await day(p0 * (1 + 0.05 * i))).rebalanced) rebalances++;
  out(`${rebalances} rebalance(s): as ETH rose the short lost and the long gained; the keeper sold WETH and topped up margin to hold ~2x.`);
  await book("After ETH +20%");

  // ---- 11. ETH -20% ----------------------------------------------------------
  out("\n## Step 11 - ETH falls 20% from there over four days");
  const p1 = await currentPrice();
  rebalances = 0;
  for (let i = 1; i <= 4; i++) if ((await day(p1 * (1 - 0.05 * i))).rebalanced) rebalances++;
  out(`${rebalances} rebalance(s): the short gained, surplus margin was withdrawn and the long leg re-levered.`);
  await book("After ETH -20%");

  // ---- 12. funding ----------------------------------------------------------------
  out("\n## Step 12 - funding turns negative (-0.03%/8h ~ -33% APR), then recovers");
  await send(SIM, d.perpMarket, c.perp.abi, "setFundingRate", [toFixed(-0.0003, 18)]);
  const f1 = await day();
  const s12 = await state();
  out(`Keeper: ${f1.rebalanced ? "rebalanced" : "no rebalance"}. Defensive mode = ${s12.strat.defensive}; basis shrunk to ${$(s12.pos.long.valueUsd)} long, ${$(s12.pos.reserve.suppliedUsd)} parked in USDC lending.`);
  await send(SIM, d.perpMarket, c.perp.abi, "setFundingRate", [toFixed(0.0002, 18)]);
  const relevered = (await day()).rebalanced || (await day()).rebalanced;
  const s12b = await state();
  out(`Funding back to +0.02%/8h (~22% APR): ${relevered ? "the carry filter approved re-levering" : "no re-lever yet"}; long leg back to ${$(s12b.pos.long.valueUsd)}.`);

  // ---- 13. forced rebalance -------------------------------------------------------
  out("\n## Step 13 - trigger a rebalance: the perp venue auto-deleverages 15% of the hedge");
  await send(SIM, d.perpMarket, c.perp.abi, "simulateAdl", [d.perpAdapter, 1500n]);
  const pre = await state();
  const [plan13, exec13] = await c.rebalanceManager.read.previewRebalance();
  out(`Delta jumped to ${pre.delta.deltaBps} bps of NAV (hard limit 500). Plan: execute=${exec13}, urgent=${plan13.urgent} (urgent bypasses the cooldown and cost filters).`);
  await keeper.tick();
  const post = await state();
  out(`After the urgent rebalance delta is ${post.delta.deltaBps} bps; hedge ratio ${(post.delta.hedgeRatioBps / 100).toFixed(2)}%.`);

  // ---- 14. PnL -----------------------------------------------------------------------
  out("\n## Step 14 - a month of carry (daily keeper, ETH drifts), then the PnL attribution");
  await send(SIM, d.perpMarket, c.perp.abi, "setFundingRate", [toFixed(0.0001, 18)]);
  let px = await currentPrice();
  for (let i = 0; i < 30; i++) {
    px *= 1 + 0.012 * Math.sin(i / 3);
    await day(px);
  }
  const s14 = await state();
  const p = s14.pnl;
  table({
    "lending income (USDC reserve)": $(p.lendingIncomeUsdc),
    "lending income (WETH long leg)": $(p.lendingIncomeWeth),
    "funding income": $(p.fundingIncome),
    "spot PnL (realised + unrealised)": $(p.spotRealizedPnl + p.spotUnrealizedPnl),
    "perp PnL (realised + unrealised)": $(p.perpRealizedPnl + p.perpUnrealizedPnl),
    "trading fees": $(-p.tradingFees),
    slippage: $(-p.slippage),
    "strategy net PnL": $(p.strategyNetPnl),
    "management fee": $(-p.managementFees),
    "performance fee": $(-p.performanceFees),
    "net PnL after fees": $(p.netPnlAfterFees),
    "reconciliation: NAV - capital - PnL": $(p.reconciliationResidualUsd, 6),
  });

  // ---- 15. risk ---------------------------------------------------------------------
  out("\n## Step 15 - risk metrics");
  const r = s14.risk;
  table(Object.fromEntries(r.metrics.map((m) => [m.label, `${m.value === null ? "n/a" : m.unit === "x" ? `${m.value.toFixed(2)}x` : pct(m.value)} (${m.level})`])));
  out(`Risk state: **${r.state}**; oracle ${r.oracle.status}; liquidation price ${r.liquidation.liquidationPrice?.toFixed(2)} vs mark ${r.liquidation.markPrice.toFixed(2)}.`);

  // ---- 16. withdraw --------------------------------------------------------------------
  out("\n## Step 16 - Alice exits");
  const bal0 = await c.usdc.read.balanceOf([ALICE.address]);
  const liquid = await c.vault.read.maxRedeem([ALICE.address]);
  await send(ALICE.key, d.vault, c.vault.abi, "redeem", [liquid, ALICE.address, ALICE.address]);
  const rest = await c.vault.read.balanceOf([ALICE.address]);
  const gross = await c.vault.read.previewRedeem([rest]);
  await send(ALICE.key, d.vault, c.vault.abi, "redeemWithUnwind", [rest, ALICE.address, ALICE.address, (gross * 995n) / 1000n]);
  const bal1 = await c.usdc.read.balanceOf([ALICE.address]);
  const received = usd(bal1 - bal0);
  const days = (Number((await pc.getBlock()).timestamp) - depositTs) / 86_400;
  out(`Standard redeem took the liquid part (${(Number(liquid) / 1e12).toFixed(2)} shares from idle + reserve); redeemWithUnwind unwound the basis pro-rata for the rest, Alice paying her own exit costs.`);
  table({
    deposited: $(100_000),
    received: $(received),
    "net return": `${((received / 100_000 - 1) * 100).toFixed(3)}%`,
    "holding period (chain days)": days.toFixed(0),
    "annualised (approx.)": `${((Math.pow(received / 100_000, 365 / days) - 1) * 100).toFixed(2)}%`,
  });
  // fee recipient still holds shares; strategy may keep a small residual
  const fin = await state();
  out(`Vault after exit: TVL ${$(fin.vault.tvlUsd)} (fee recipient's shares), perp size ${fin.pos.perp.size.toFixed(6)} ETH.`);

  // guardian path: verify the emergency controls exist and work on what's left
  await send(GUARDIAN, d.emergencyController, c.emergency.abi, "emergencyUnwind", [toFixed(1, 18), toFixed(1_000_000, 18)]);
  out("Guardian emergency unwind on the remainder: shutdown mode, all USDC back in the vault.");

  const path = resolve(import.meta.dirname, "../../docs/demo-output.md");
  writeFileSync(path, `${md.join("\n")}\n`);
  console.log(`\ntranscript written to ${path}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
