/**
 * JSON Schemas for the OpenAPI document. Objects are `additionalProperties: true` so the serializer
 * never silently drops a field the TS types carry; the listed properties are what is documented.
 */
type S = Record<string, unknown>;

const num = (description?: string): S => ({ type: "number", ...(description ? { description } : {}) });
const numN = (description?: string): S => ({ type: ["number", "null"], ...(description ? { description } : {}) });
const int = (description?: string): S => ({ type: "integer", ...(description ? { description } : {}) });
const str = (description?: string, extra: S = {}): S => ({ type: "string", ...(description ? { description } : {}), ...extra });
const bool = (description?: string): S => ({ type: "boolean", ...(description ? { description } : {}) });
const arr = (items: S): S => ({ type: "array", items });
const obj = (properties: Record<string, S>, description?: string): S => ({
  type: "object",
  additionalProperties: true,
  properties,
  ...(description ? { description } : {}),
});

const riskState = str("NORMAL | WARNING | HIGH_RISK | EMERGENCY", { enum: ["NORMAL", "WARNING", "HIGH_RISK", "EMERGENCY"] });
const chainMeta = {
  chainId: int(),
  blockNumber: int(),
  blockTimestamp: int("Chain time (unix s). The local demo warps time, so this is the simulated clock."),
};

export const schemas = {
  vault: obj({
    ...chainMeta,
    address: str(),
    asset: str(),
    name: str(),
    symbol: str(),
    tvlUsd: num("Total assets: idle USDC + strategy NAV"),
    sharePrice: num("USDC per share"),
    totalSupply: num(),
    idleUsd: num(),
    availableLiquidityUsd: num("Withdrawable without trading (idle + lending reserve)"),
    depositCapUsd: num(),
    operational: bool("false while the oracle is unhealthy and positions are open"),
    depositsPaused: bool(),
    strategyPaused: bool(),
    shutdown: bool(),
  }),
  metrics: obj({
    ...chainMeta,
    tvlUsd: num(),
    sharePrice: num(),
    netApy: numN("Realised, annualised share-price growth over the trailing 30 days (fraction)"),
    grossApy: numN("Realised carry (lending + funding) / average TVL before costs and fees"),
    estimatedNetApy: num("Forward-looking estimate at current rates (simulator estimation engine)"),
    lendingApy: num(),
    usdcSupplyApr: num(),
    wethSupplyApr: num(),
    fundingRatePer8h: num(),
    fundingApr: num(),
    netDeltaBps: num("Integer bps of total NAV, as the contracts compute it (truncated toward zero)"),
    netDeltaBpsExact: num("Same ratio without truncation"),
    netDeltaUsd: num(),
    hedgeRatio: num(),
    leverage: num(),
    liquidationDistanceBps: numN(),
    drawdownBps: num(),
    totalPnlUsd: num("Strategy PnL net of vault fees"),
    riskState,
    ethPrice: num(),
  }),
  positions: obj({
    ...chainMeta,
    ethPrice: num(),
    oracleHealthy: bool(),
    idle: obj({ vaultUsd: num(), strategyFloatUsd: num() }),
    reserve: obj({ suppliedUsd: num(), principalUsd: num(), interestUsd: num(), supplyApr: num(), utilization: num(), withdrawableUsd: num() }),
    long: obj({ wethQty: num(), valueUsd: num(), principalQty: num(), interestQty: num(), supplyApr: num(), utilization: num(), costBasisUsd: num() }),
    perp: obj({
      size: num("ETH, negative = short"),
      entryPrice: num(),
      markPrice: num(),
      markEntryPrice: num(),
      notionalUsd: num(),
      marginUsd: num(),
      equityUsd: num(),
      unrealizedPnlUsd: num(),
      pendingFundingUsd: num(),
      leverage: num(),
      liquidationPrice: numN(),
      liquidationDistanceBps: numN(),
      maintenanceMarginUsd: num(),
      collateralRatio: numN(),
      fundingRatePer8h: num(),
    }),
    allocation: obj({ reservePct: num(), longPct: num(), perpPct: num(), idlePct: num() }),
  }),
  delta: obj({
    ...chainMeta,
    longExposureUsd: num(),
    shortExposureUsd: num(),
    grossExposureUsd: num(),
    netDeltaQty: num(),
    netDeltaUsd: num(),
    deltaBps: num("Net delta as a share of total NAV, integer bps (on-chain value)"),
    deltaBpsExact: num("netDeltaUsd / totalNav x 1e4 without truncation"),
    hedgeRatioBps: num(),
    targetPerpSize: num(),
    requiredPerpSizeChange: num(),
    requiredHedgeChangeUsd: num(),
    bandBps: num(),
    effectiveBandBps: num("Tolerance after volatility scaling"),
    withinBand: bool(),
  }),
  risk: obj({
    ...chainMeta,
    state: riskState,
    persistedState: riskState,
    flags: arr(str()),
    metrics: arr(obj({ key: str(), label: str(), value: numN(), unit: str('"bps" | "x" | "apr" - "apr" is an annualised rate in bps (-500 = -5% APR)'), level: riskState, higherIsWorse: bool(), thresholds: obj({ warn: num(), high: num(), critical: numN() }) })),
    peakSharePrice: num(),
    oracle: obj({ status: str(), price: num(), lastGoodPrice: num(), lastGoodAt: int(), shutdown: bool() }),
    liquidation: obj({ markPrice: num(), liquidationPrice: numN(), distanceBps: numN(), safetyBufferBps: numN(), leverage: num() }),
    circuitBreakers: obj({ depositsPaused: bool(), strategyPaused: bool(), shutdown: bool() }),
    limits: obj({ maxSlippageBps: num(), maxPositionNotionalUsd: num() }),
  }),
  funding: obj({
    ...chainMeta,
    ratePer8h: num(),
    apr: num(),
    settledFundingUsd: num(),
    pendingFundingUsd: num(),
    cumulativeFundingUsd: num(),
    shortNotionalUsd: num(),
    annualizedIncomeUsd: num(),
    history: arr(obj({ ts: int(), ratePer8h: num(), cumulativeFundingUsd: num() })),
    settlements: arr(obj({ ts: int(), blockNumber: int(), amountUsd: num(), txHash: str() })),
  }),
  pnl: obj({
    ...chainMeta,
    lendingIncomeUsdc: num(),
    lendingIncomeWeth: num(),
    fundingIncome: num(),
    spotRealizedPnl: num(),
    spotUnrealizedPnl: num(),
    perpRealizedPnl: num(),
    perpUnrealizedPnl: num(),
    tradingFees: num(),
    slippage: num(),
    badDebtAbsorbed: num(),
    strategyNetPnl: num(),
    managementFees: num(),
    performanceFees: num(),
    netPnlAfterFees: num(),
    netCapital: num(),
    strategyNav: num(),
    reconciliationResidualUsd: num("strategyNav - netCapital - strategyNetPnl; ~0 by construction"),
  }),
  fees: obj({
    ...chainMeta,
    managementFeeBps: num(),
    performanceFeeBps: num(),
    withdrawalFeeBps: num(),
    caps: obj({ managementFeeBps: num(), performanceFeeBps: num(), withdrawalFeeBps: num() }),
    highWaterMark: num(),
    sharePrice: num(),
    aboveHighWaterMark: bool(),
    totalManagementFeesUsd: num(),
    totalPerformanceFeesUsd: num(),
    feeRecipient: str(),
    feeRecipientShares: num(),
    feeRecipientValueUsd: num(),
    lastAccrual: int(),
  }),
  strategy: obj({
    ...chainMeta,
    targets: obj({ leverage: num(), hedgeRatio: num(), reservePct: num(), defensiveReservePct: num() }),
    bounds: obj({}),
    params: obj({}),
    effectiveLeverage: num(),
    annualizedVolBps: num(),
    defensive: bool(),
    lastRebalanceAt: int(),
    rebalanceCount: int(),
    nextPlan: obj({ execute: bool(), urgent: bool(), triggers: arr(str()), sweepIdleUsd: num(), longUsdDelta: num(), marginDelta: num(), estimatedCostUsd: num() }),
  }),
  performance: obj({
    points: arr(obj({ ts: int(), tvlUsd: num(), sharePrice: num(), ethPrice: num(), netDeltaBps: num(), leverage: num(), drawdownBps: num(), fundingRatePer8h: num(), apy7d: numN(), apy30d: numN() })),
    summary: obj({ fromTs: int(), toTs: int(), periodReturn: num(), annualizedReturn: numN(), maxDrawdownBps: num(), volatilityAnnual: numN(), sharpe: numN(), rebalances: int() }),
  }),
  apy: obj({
    estimate: obj({}, "ApyEstimate from the simulator estimation engine, at the live (vol-scaled) leverage"),
    optimizer: obj({
      current: obj({}, "Estimate at the live configuration"),
      best: obj({}, "Best feasible grid point"),
      frontier: arr(obj({ leverage: num(), reservePct: num(), netApy: num(), liquidationMovePct: num(), rebalancesPerYear: num(), feasible: bool() })),
      constraints: obj({ minLiquidationMovePct: num(), maxRebalancesPerYear: num(), maxLiquidationProb7d: num() }),
      recommendation: str(),
    }),
  }),
  scenarios: arr(obj({ id: str(), name: str(), description: str(), ethMovePct: num(), withKeeper: obj({}), withoutKeeper: obj({}) })),
  rebalances: arr(
    obj({ id: int(), ts: int(), blockNumber: int(), txHash: str(), triggers: arr(str()), urgent: bool(), longUsdDelta: num(), marginDelta: num(), perpSizeChange: num(), preDeltaBps: num(), postDeltaBps: num(), preLeverage: num(), postLeverage: num(), estimatedCostUsd: num(), realizedCostUsd: num() }),
  ),
  alerts: arr(
    obj({
      id: int(),
      key: str(),
      severity: str("INFO | WARNING | CRITICAL"),
      title: str(),
      message: str(),
      value: numN("Observed value, in `unit`"),
      threshold: numN("Threshold crossed, in `unit`"),
      unit: { type: ["string", "null"], description: 'bps | apr (annualised rate in bps) | usd | null when the alert carries no number' },
      openedAt: int("Chain time"),
      resolvedAt: { type: ["integer", "null"], description: "Chain time" },
      active: bool(),
    }),
  ),
  riskEvents: arr(
    obj({
      id: int(),
      ts: int("Chain time"),
      blockNumber: int(),
      txHash: str(),
      kind: str(),
      previousState: { type: ["string", "null"] },
      newState: { type: ["string", "null"] },
      flags: { type: ["integer", "null"], description: "Raw on-chain risk-flag bitmask" },
      flagNames: arr(str("Decoded risk flags")),
    }),
  ),
  transactions: arr(obj({ id: int(), kind: str(), ts: int(), blockNumber: int(), txHash: str(), owner: str(), assetsUsd: num(), shares: num() })),
  health: obj({ ok: bool(), chain: obj({}), db: obj({}), indexer: obj({}), keeper: obj({}) }),
  simulationRequest: {
    type: "object",
    required: ["type"],
    properties: {
      type: str("scenario | custom | montecarlo | optimizer", { enum: ["scenario", "custom", "montecarlo", "optimizer"] }),
      scenarioId: str("A..J (type=scenario)"),
      priceMovePct: num("type=custom (required): ETH move in percent, e.g. -30"),
      moveDays: num("type=custom (required): days over which the move happens"),
      horizonDays: num("type=custom (required): total simulated days"),
      fundingRatePer8h: num(),
      usdcUtilization: num(),
      wethUtilization: num(),
      oracleOutageDays: num(),
      liquidityMultiplier: num(),
      leverageBps: num(),
      reserveBps: num(),
      paths: int("type=montecarlo, max 500"),
      days: int("type=montecarlo, max 730"),
      seed: int(),
      tvl: num(),
    },
    additionalProperties: false,
  },
  simulationResult: obj({ id: int(), type: str(), result: obj({}) }),
  storedSimulation: obj({
    id: int(),
    createdAt: str("Wall-clock time the simulation ran (ISO 8601) - not chain time"),
    kind: str(),
    input: obj({}),
    result: obj({}),
  }),
  error: obj({ error: str(), message: str() }),
} as const;
