import type { Chain_ } from "./clients";

/**
 * Reads the entire protocol state *at one block* so every derived view is internally consistent
 * (a snapshot never mixes a pre-rebalance position with a post-rebalance PnL). ~45 view calls go out
 * over a batched JSON-RPC transport.
 */
export async function readRawState(chain: Chain_, blockNumber?: bigint) {
  const c = chain.contracts;
  const d = chain.deployment;
  const bn = blockNumber ?? (await chain.publicClient.getBlockNumber());
  const at = { blockNumber: bn } as const;

  const [
    block,
    totalAssets,
    totalSupply,
    sharePrice,
    idle,
    liquidity,
    depositCap,
    operational,
    name,
    symbol,
    depositsPaused,
    strategyPaused,
    shutdown,
    snapshot,
    pnl,
    riskReport,
    persistedState,
    peakSharePrice,
    riskConfig,
    targets,
    bounds,
    params,
    effectiveLeverageBps,
    annualizedVolBps,
    lastRebalanceAt,
    rebalanceCount,
    preview,
  ] = await Promise.all([
    chain.publicClient.getBlock({ blockNumber: bn }),
    c.vault.read.totalAssets(at),
    c.vault.read.totalSupply(at),
    c.vault.read.sharePrice(at),
    c.vault.read.idleAssets(at),
    c.vault.read.availableLiquidity(at),
    c.vault.read.depositCap(at),
    c.vault.read.isOperational(at),
    c.vault.read.name(at),
    c.vault.read.symbol(at),
    c.emergency.read.depositsPaused(at),
    c.emergency.read.strategyPaused(at),
    c.emergency.read.isShutdown(at),
    c.positionManager.read.snapshot(at),
    c.positionManager.read.pnl(at),
    c.riskManager.read.assess(at),
    c.riskManager.read.currentState(at),
    c.riskManager.read.peakSharePrice(at),
    c.riskManager.read.config(at),
    c.rebalanceManager.read.targets(at),
    c.rebalanceManager.read.bounds(at),
    c.rebalanceManager.read.params(at),
    c.rebalanceManager.read.effectiveLeverageBps(at),
    c.rebalanceManager.read.annualizedVolBps(at),
    c.rebalanceManager.read.lastRebalanceAt(at),
    c.rebalanceManager.read.rebalanceCount(at),
    c.rebalanceManager.read.previewRebalance(at),
  ]);

  const [
    mgmtBps,
    perfBps,
    withdrawalBps,
    hwm,
    lastAccrual,
    totalMgmt,
    totalPerf,
    feeRecipient,
    maxMgmt,
    maxPerf,
    maxWithdrawal,
    oracleRead,
    lastGood,
    oracleShutdown,
    usdcPrincipal,
    wethPrincipal,
    usdcInterest,
    wethInterest,
    usdcWithdrawable,
    usdcUtilization,
    wethUtilization,
    markAccounting,
    accountStats,
    perpPosition,
    accounting,
    deltaReport,
    liquidationReport,
  ] = await Promise.all([
    c.feeManager.read.managementFeeBps(at),
    c.feeManager.read.performanceFeeBps(at),
    c.feeManager.read.withdrawalFeeBps(at),
    c.feeManager.read.highWaterMark(at),
    c.feeManager.read.lastAccrual(at),
    c.feeManager.read.totalManagementFeesAssets(at),
    c.feeManager.read.totalPerformanceFeesAssets(at),
    c.feeManager.read.feeRecipient(at),
    c.feeManager.read.MAX_MANAGEMENT_FEE_BPS(at),
    c.feeManager.read.MAX_PERFORMANCE_FEE_BPS(at),
    c.feeManager.read.MAX_WITHDRAWAL_FEE_BPS(at),
    c.oracle.read.tryGetPrice([d.weth], at),
    c.oracle.read.lastGoodPrice([d.weth], at),
    c.oracle.read.isShutdown(at),
    c.lendingAdapter.read.principalOf([d.usdc], at),
    c.lendingAdapter.read.principalOf([d.weth], at),
    c.lendingAdapter.read.cumulativeInterest([d.usdc], at),
    c.lendingAdapter.read.cumulativeInterest([d.weth], at),
    c.lendingAdapter.read.withdrawable([d.usdc], at),
    c.lendingAdapter.read.utilization([d.usdc], at),
    c.lendingAdapter.read.utilization([d.weth], at),
    c.perpAdapter.read.markAccounting(at),
    c.perpAdapter.read.accountStats(at),
    c.perpAdapter.read.position(at),
    c.strategy.read.accounting(at),
    c.positionManager.read.deltaReport([BigInt(targets.hedgeRatioBps)], at),
    c.positionManager.read.liquidationReport([BigInt(riskConfig.liquidationDistance.high)], at),
  ]);

  const [feeRecipientShares] = await Promise.all([c.vault.read.balanceOf([feeRecipient], at)]);
  const feeRecipientAssets = await c.vault.read.convertToAssets([feeRecipientShares], at);

  return {
    blockNumber: bn,
    timestamp: block.timestamp,
    vault: { totalAssets, totalSupply, sharePrice, idle, liquidity, depositCap, operational, name, symbol },
    emergency: { depositsPaused, strategyPaused, shutdown },
    snapshot,
    pnl,
    risk: { report: riskReport, persistedState, peakSharePrice, config: riskConfig },
    rebalance: { targets, bounds, params, effectiveLeverageBps, annualizedVolBps, lastRebalanceAt, rebalanceCount, preview },
    fees: {
      mgmtBps,
      perfBps,
      withdrawalBps,
      hwm,
      lastAccrual,
      totalMgmt,
      totalPerf,
      feeRecipient,
      feeRecipientShares,
      feeRecipientAssets,
      caps: { maxMgmt, maxPerf, maxWithdrawal },
    },
    oracle: { price: oracleRead[0], status: oracleRead[1], lastGoodPrice: lastGood[0], lastGoodAt: lastGood[1], shutdown: oracleShutdown },
    lending: { usdcPrincipal, wethPrincipal, usdcInterest, wethInterest, usdcWithdrawable, usdcUtilization, wethUtilization },
    perp: { markAccounting, accountStats, position: perpPosition },
    accounting,
    deltaReport,
    liquidationReport,
  };
}

export type RawState = Awaited<ReturnType<typeof readRawState>>;
