// Exports forge artifacts into a typed TS module (`as const` so viem infers every call/event).
// Run after `forge build`: node scripts/export-abis.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const contracts = [
  "DeltaNeutralVault",
  "StrategyManager",
  "PositionManager",
  "RiskManager",
  "RebalanceManager",
  "FeeManager",
  "OracleManager",
  "EmergencyController",
  "AccessRegistry",
  "LendingAdapter",
  "PerpAdapter",
  "SwapAdapter",
  "MockERC20",
  "MockAggregatorV3",
  "MockLendingProtocol",
  "MockPerpetualMarket",
  "MockSpotDEX",
];

let out = "// AUTO-GENERATED by scripts/export-abis.mjs from forge artifacts. Do not edit by hand.\n\n";
for (const name of contracts) {
  const artifact = JSON.parse(readFileSync(resolve(root, `out/${name}.sol/${name}.json`), "utf8"));
  const id = name.charAt(0).toLowerCase() + name.slice(1);
  out += `export const ${id}Abi = ${JSON.stringify(artifact.abi)} as const;\n\n`;
}
writeFileSync(resolve(root, "shared/src/abis.ts"), out);
console.log(`exported ${contracts.length} ABIs -> shared/src/abis.ts`);
